### ISSUE TITLE
Два бага.

### ISSUE THREAD

**Issue by Heyter** [videosegments/videosegments#12]
Первая загрузка видео и нет панельки VS, но если обновить страницу то она появляется.
Так же заметил, что отсегментированные видео не работают, тобишь сегменты в видео присутствуют, но рекламу не пропускает. (хотя в настройках стоит пропускать) (Но если обновить видео 3 раз, то тогда пропускает)

Translated by videosegments
On first load missing segmentation panel. Page refreshing fixes this issue. 
Sometimes extension wont rewind segments to skip.

**Comment by videosegments** [comment]
Подтверждаю это странное поведение. Попытаюсь починить как можно быстрее (этот баг уже был ранее, потом был исправлен, сейчас появился опять).
Confirmed such strange behavior. We will try to fix it ASAP (this bug was in previous versions then in was fixed and now appears again).

**Comment by videosegments** [comment]
Исправил ошибку с округлением чисел. Залью новую версию через пару часов. Спасибо за сообщение о багах!
Fixed issues with rounding. Will upload new version in few hours. Thank you for your feedback!
