### ISSUE TITLE
[Firefox Nightly] Anonymous User Even When Logged In

### ISSUE THREAD

**Issue by TteokbokkiNari** [videosegments/videosegments#19]
I logged in, yet I still got a pop-up about being an anonymous user, and being unable to send in a video with under 50K views? 

I tried logging out and in again, but same issue happens.

**Comment by videosegments** [comment]
Sorry for late responce and inconvenience. 
I've had no time to add proper notifications. We have few limits for registered users too, based on reputation score (it's hidden on review site, in "reasons to register): https://videosegments.org/limits.html
If you tell me your login, I can increase your reputation to bypass this limit (main reason for this system was to prevent obviously intentionally wrong segmentation from new users).

**Comment by videosegments** [comment]
I've greatly lowered some limits and updated information on page (https://videosegments.org/limits.html)

**Comment by TteokbokkiNari** [comment]
Ah, no worries. :) 

Just trying to help other users of this addon. 
VideoSegHelper is my ID if it helps in any way.

**Comment by videosegments** [comment]
Reasons of auto-reject clarified in 1.9.2 version.
