### ISSUE TITLE
[Firefox Nightly][Website/Addon Feedback] 

### ISSUE THREAD

**Issue by TteokbokkiNari** [videosegments/videosegments#20]
Would be neat if you could somehow find out about your account information. 

I made an account, but I have no idea where to check my reputation score, which videos I've sent in, any way to edit profile info etc.

**Comment by videosegments** [comment]
I'll add today-tomorrow reputation score to "community" tab.
Next item in my list is to fully overhaul review system, but this will take some time. I want to add to community tab user's recently sended videos and desicions (quick reference to https://db.videosegments.org/queue.php, but only for your submissions). Moreover, I want to add ability to share segmentation with friends (who have extension) right after submission, even before it's reviewed (it's ready now, but these links die after review). I'll try to add this feature soon (with mentioned limit).

**Comment by videosegments** [comment]
Added in 1.9.2.
