### ISSUE TITLE
[Firefox] Alert Box Design Difference Between Normal & Expert Mode

### ISSUE THREAD

**Issue by TteokbokkiNari** [videosegments/videosegments#22]
The alert box design seems to differ between both editing modes, see pictures below:
![firefox_2018-05-22_22-18-03](https://user-images.githubusercontent.com/6826910/40391326-28d7d3b2-5e18-11e8-9b5b-7c7dbc334033.jpg)

![firefox_2018-05-22_22-19-19](https://user-images.githubusercontent.com/6826910/40391335-2c3c7f8a-5e18-11e8-836f-a70f897c8f9c.jpg)

**Comment by videosegments** [comment]
Thank you for report! Issue is fixed in 1.9.3. I'll upload this version tomorrow.
