### ISSUE TITLE
Use <input type="color"> instead of Spectrum Colorpicker

### ISSUE THREAD

**Issue by bershanskiy** [videosegments/videosegments#25]
While using the extension, I noticed you use a library "Spectrum Colorpicker" to pick the colors in the settings. May I inquire what's the benefit of it over `<input type="color">`?

As far as I see, the point of the library is to implement color picker for browsers that do not support `<input type="color">`, but all browsers capable of running the extension already support it. Specifically, you use Promises in `background.js` [supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility) by Chrome 32+ and Firefox 29+, meanwhile, `input` is [supported](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color#Browser_compatibility) by Chrome 20+ and Firefox 29+.

**Comment by videosegments** [comment]
I find `input type="color"` awkward:

- Colors can't be picked from HTML/HSV/HSL codes.
- Interface is a little bit outdated (this pallete was in Window XP).
- It locks browser so you can't switch tab/close browser/do another action unless you close it.

These are main reasons why I decided to use "Spectrum Colorpicker" over regular `input`.

**Comment by bershanskiy** [comment]
@videosegments Thanks for the prompt reply! Closing this as a non-issue then.
