### ISSUE TITLE
Make your local Database have precedence

### ISSUE THREAD

**Issue by CorePoint** [videosegments/videosegments#8]
It would be nice to have an option (or make it default) to have your local db have precedence over the online db.

People just have different views on how the segments should be defined.
I for my self wouldn't mark the time in a music video where there is no voice yet (but instrumentals) as a cutscene, other people seem to want it like that.

**Comment by videosegments** [comment]
Yes, this is in our primary list of "ToDo". Will try to deliver this option ASAP (probably this weekend, maybe earlier). We also add later user-created databases because we do realize that it's question of taste.

**Comment by CorePoint** [comment]
Good to hear! Then i can get back to contributing segment data. :)

**Comment by videosegments** [comment]
Btw, if you contact us through facebook private message or email (don't forget to say that it is you), we can give you login-pass (not related to social networks) so you will not see captcha on send (if you send less than 1 video per minute) and (if you want) your segmentation will go directly to official database (without review).

**Comment by videosegments** [comment]
Fixed in 1.4.6.
Updated in Firefox and Chrome.
Will send update to Opera a little bit later.

**Comment by CorePoint** [comment]
Hey, i have sent you a mail. :)
